/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShortUrlImport } from './routes/$shortUrl'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ShortUrlRoute = ShortUrlImport.update({
  id: '/$shortUrl',
  path: '/$shortUrl',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$shortUrl': {
      id: '/$shortUrl'
      path: '/$shortUrl'
      fullPath: '/$shortUrl'
      preLoaderRoute: typeof ShortUrlImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortUrl': typeof ShortUrlRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortUrl': typeof ShortUrlRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$shortUrl': typeof ShortUrlRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$shortUrl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$shortUrl'
  id: '__root__' | '/' | '/$shortUrl'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortUrlRoute: typeof ShortUrlRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortUrlRoute: ShortUrlRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$shortUrl"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$shortUrl": {
      "filePath": "$shortUrl.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
